// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RestaurantPOS.Data;

#nullable disable

namespace RestaurantPOS.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260715213130_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RestaurantPOS.Data.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("IconName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IconName = "Hamburger",
                            Name = "Burgers"
                        },
                        new
                        {
                            Id = 2,
                            IconName = "Pizza",
                            Name = "Pizza"
                        },
                        new
                        {
                            Id = 3,
                            IconName = "CupWater",
                            Name = "Drinks"
                        },
                        new
                        {
                            Id = 4,
                            IconName = "IceCream",
                            Name = "Desserts"
                        });
                });

            modelBuilder.Entity("RestaurantPOS.Data.Entities.MenuItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Barcode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ImagePath")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int>("PreparationTimeMinutes")
                        .HasColumnType("integer");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("MenuItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Barcode = "10001",
                            CategoryId = 1,
                            Description = "Beef patty with cheese",
                            ImagePath = "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=400&q=80",
                            Name = "Classic Cheeseburger",
                            PreparationTimeMinutes = 5,
                            Price = 9.99m,
                            StockQuantity = 50
                        },
                        new
                        {
                            Id = 2,
                            Barcode = "10002",
                            CategoryId = 1,
                            Description = "Two beef patties with bacon",
                            ImagePath = "https://images.unsplash.com/photo-1594212202875-8eb5a8820c75?w=400&q=80",
                            Name = "Double Bacon Burger",
                            PreparationTimeMinutes = 8,
                            Price = 12.99m,
                            StockQuantity = 30
                        },
                        new
                        {
                            Id = 3,
                            Barcode = "20001",
                            CategoryId = 2,
                            Description = "Large pepperoni pizza",
                            ImagePath = "https://images.unsplash.com/photo-1628840042765-356cda07504e?w=400&q=80",
                            Name = "Pepperoni Pizza",
                            PreparationTimeMinutes = 12,
                            Price = 15.99m,
                            StockQuantity = 20
                        },
                        new
                        {
                            Id = 4,
                            Barcode = "20002",
                            CategoryId = 2,
                            Description = "Classic cheese and tomato",
                            ImagePath = "https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=400&q=80",
                            Name = "Margherita Pizza",
                            PreparationTimeMinutes = 10,
                            Price = 14.99m,
                            StockQuantity = 25
                        },
                        new
                        {
                            Id = 5,
                            Barcode = "30001",
                            CategoryId = 3,
                            Description = "Can of Coke",
                            ImagePath = "https://images.unsplash.com/photo-1622483767028-3f66f32aef97?w=400&q=80",
                            Name = "Coca Cola",
                            PreparationTimeMinutes = 1,
                            Price = 2.50m,
                            StockQuantity = 200
                        },
                        new
                        {
                            Id = 6,
                            Barcode = "30002",
                            CategoryId = 3,
                            Description = "Fresh brewed iced tea",
                            ImagePath = "https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=400&q=80",
                            Name = "Iced Tea",
                            PreparationTimeMinutes = 2,
                            Price = 3.00m,
                            StockQuantity = 150
                        },
                        new
                        {
                            Id = 7,
                            Barcode = "40001",
                            CategoryId = 4,
                            Description = "Vanilla ice cream with chocolate syrup",
                            ImagePath = "https://images.unsplash.com/photo-1563805042-7684c8a9e9ce?w=400&q=80",
                            Name = "Chocolate Sundae",
                            PreparationTimeMinutes = 3,
                            Price = 5.99m,
                            StockQuantity = 40
                        });
                });

            modelBuilder.Entity("RestaurantPOS.Data.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("EstimatedCompletionTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int?>("TableId")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TableId");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EstimatedCompletionTime = new DateTime(2026, 7, 16, 12, 15, 0, 0, DateTimeKind.Local),
                            OrderDate = new DateTime(2026, 7, 16, 12, 0, 0, 0, DateTimeKind.Local),
                            Status = "Completed",
                            TableId = 1,
                            TotalAmount = 45.20m,
                            UserId = 2
                        },
                        new
                        {
                            Id = 2,
                            EstimatedCompletionTime = new DateTime(2026, 7, 16, 13, 10, 0, 0, DateTimeKind.Local),
                            OrderDate = new DateTime(2026, 7, 16, 13, 0, 0, 0, DateTimeKind.Local),
                            Status = "Completed",
                            TableId = 2,
                            TotalAmount = 35.40m,
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            EstimatedCompletionTime = new DateTime(2026, 7, 16, 14, 12, 0, 0, DateTimeKind.Local),
                            OrderDate = new DateTime(2026, 7, 16, 14, 0, 0, 0, DateTimeKind.Local),
                            Status = "Completed",
                            TableId = 3,
                            TotalAmount = 15.99m,
                            UserId = 2
                        });
                });

            modelBuilder.Entity("RestaurantPOS.Data.Entities.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("ExtraCharge")
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("MenuItemId")
                        .HasColumnType("integer");

                    b.Property<int>("OrderId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<string>("Remarks")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("MenuItemId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("RestaurantPOS.Data.Entities.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AmountPaid")
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("OrderId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("Payments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AmountPaid = 45.20m,
                            OrderId = 1,
                            PaymentDate = new DateTime(2026, 7, 16, 12, 30, 0, 0, DateTimeKind.Local),
                            PaymentMethod = "Card"
                        },
                        new
                        {
                            Id = 2,
                            AmountPaid = 35.40m,
                            OrderId = 2,
                            PaymentDate = new DateTime(2026, 7, 16, 13, 20, 0, 0, DateTimeKind.Local),
                            PaymentMethod = "Cash"
                        },
                        new
                        {
                            Id = 3,
                            AmountPaid = 15.99m,
                            OrderId = 3,
                            PaymentDate = new DateTime(2026, 7, 16, 14, 15, 0, 0, DateTimeKind.Local),
                            PaymentMethod = "Card"
                        });
                });

            modelBuilder.Entity("RestaurantPOS.Data.Entities.Table", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("TableNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Tables");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 4,
                            Status = "Available",
                            TableNumber = 1
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 2,
                            Status = "Available",
                            TableNumber = 2
                        },
                        new
                        {
                            Id = 3,
                            Capacity = 6,
                            Status = "Occupied",
                            TableNumber = 3
                        },
                        new
                        {
                            Id = 4,
                            Capacity = 4,
                            Status = "Available",
                            TableNumber = 4
                        },
                        new
                        {
                            Id = 5,
                            Capacity = 8,
                            Status = "Reserved",
                            TableNumber = 5
                        });
                });

            modelBuilder.Entity("RestaurantPOS.Data.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PasswordHash = "admin",
                            Role = "Admin",
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            PasswordHash = "1234",
                            Role = "Cashier",
                            Username = "cashier1"
                        },
                        new
                        {
                            Id = 3,
                            PasswordHash = "kitchen",
                            Role = "Kitchen",
                            Username = "kitchen1"
                        });
                });

            modelBuilder.Entity("RestaurantPOS.Data.Entities.MenuItem", b =>
                {
                    b.HasOne("RestaurantPOS.Data.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("RestaurantPOS.Data.Entities.Order", b =>
                {
                    b.HasOne("RestaurantPOS.Data.Entities.Table", "Table")
                        .WithMany()
                        .HasForeignKey("TableId");

                    b.HasOne("RestaurantPOS.Data.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Table");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RestaurantPOS.Data.Entities.OrderItem", b =>
                {
                    b.HasOne("RestaurantPOS.Data.Entities.MenuItem", "MenuItem")
                        .WithMany()
                        .HasForeignKey("MenuItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RestaurantPOS.Data.Entities.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MenuItem");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("RestaurantPOS.Data.Entities.Payment", b =>
                {
                    b.HasOne("RestaurantPOS.Data.Entities.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("RestaurantPOS.Data.Entities.Order", b =>
                {
                    b.Navigation("OrderItems");
                });
#pragma warning restore 612, 618
        }
    }
}
